/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programacion_segundoexamen;

/**
 *
 * @author Camila Cueva
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Cuenta
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNSalir = new javax.swing.JButton();
        BTNCuentaAhorro = new javax.swing.JButton();
        btnCuentaPrestamo = new javax.swing.JButton();
        btnBuscarCuentaAhorro = new javax.swing.JButton();
        btnCuentaHipoteca = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnBuscarCuentaHipoteca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNSalir.setText("SALIR");
        BTNSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSalirActionPerformed(evt);
            }
        });

        BTNCuentaAhorro.setText("CUENTA AHORRO");
        BTNCuentaAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCuentaAhorroActionPerformed(evt);
            }
        });

        btnCuentaPrestamo.setText("CUENTA PRESTAMO");

        btnBuscarCuentaAhorro.setText("BUSCAR CUENTA AHORO");
        btnBuscarCuentaAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCuentaAhorroActionPerformed(evt);
            }
        });

        btnCuentaHipoteca.setText("CUENTA HIPOTECA");

        jButton1.setText("CREAR NUEVA CUENTA");
        jButton1.setActionCommand("CUENTA\n");

        btnBuscarCuentaHipoteca.setText("BUSCAR CUENTA HIPOTECA");
        btnBuscarCuentaHipoteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCuentaHipotecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BTNSalir))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarCuentaHipoteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarCuentaAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCuentaHipoteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCuentaPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNCuentaAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BTNSalir)
                .addGap(51, 51, 51)
                .addComponent(BTNCuentaAhorro)
                .addGap(18, 18, 18)
                .addComponent(btnCuentaPrestamo)
                .addGap(18, 18, 18)
                .addComponent(btnCuentaHipoteca)
                .addGap(21, 21, 21)
                .addComponent(btnBuscarCuentaAhorro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarCuentaHipoteca)
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BTNSalirActionPerformed

    private void BTNCuentaAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCuentaAhorroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNCuentaAhorroActionPerformed

    private void btnBuscarCuentaAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCuentaAhorroActionPerformed
        BuscarCuentaAhorro buscar = new BuscarCuentaAhorro();
        buscar.setVisible(true);

    }//GEN-LAST:event_btnBuscarCuentaAhorroActionPerformed

    private void btnBuscarCuentaHipotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCuentaHipotecaActionPerformed
        BuscarCuentaHipoteca buscar = new BuscarCuentaHipoteca();
        buscar.setVisible(true);
    }//GEN-LAST:event_btnBuscarCuentaHipotecaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCuentaAhorro;
    private javax.swing.JButton BTNSalir;
    private javax.swing.JButton btnBuscarCuentaAhorro;
    private javax.swing.JButton btnBuscarCuentaHipoteca;
    private javax.swing.JButton btnCuentaHipoteca;
    private javax.swing.JButton btnCuentaPrestamo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
